<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-15T20:58:44 JST" name="Suite" finished-at="2025-03-15T21:00:41 JST" duration-ms="117704">
    <groups>
    </groups>
    <test started-at="2025-03-15T20:58:44 JST" name="Submit Order Test" finished-at="2025-03-15T20:59:27 JST" duration-ms="43871">
      <class name="automation.test.SubmitOrderTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automation.test.SubmitOrderTest@795509d9]" started-at="2025-03-15T20:58:44 JST" name="launchApplication" finished-at="2025-03-15T20:59:23 JST" duration-ms="38999" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:automation.test.SubmitOrderTest@795509d9]" started-at="2025-03-15T20:59:23 JST" name="submitOrder" finished-at="2025-03-15T20:59:27 JST" duration-ms="4614" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automation.test.SubmitOrderTest@795509d9]" started-at="2025-03-15T20:59:27 JST" name="tearDown" finished-at="2025-03-15T20:59:27 JST" duration-ms="169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automation.test.SubmitOrderTest -->
    </test> <!-- Submit Order Test -->
    <test started-at="2025-03-15T20:59:28 JST" name="Error Validation Test" finished-at="2025-03-15T21:00:41 JST" duration-ms="73707">
      <class name="automation.test.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automation.test.ErrorValidationsTest@5b799640]" started-at="2025-03-15T20:59:28 JST" name="launchApplication" finished-at="2025-03-15T21:00:01 JST" duration-ms="33677" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:automation.test.ErrorValidationsTest@5b799640]" started-at="2025-03-15T21:00:01 JST" name="productErrorValidation" finished-at="2025-03-15T21:00:05 JST" duration-ms="3905" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automation.test.ErrorValidationsTest@5b799640]" started-at="2025-03-15T21:00:05 JST" name="tearDown" finished-at="2025-03-15T21:00:05 JST" duration-ms="145" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:automation.test.ErrorValidationsTest@5b799640]" started-at="2025-03-15T21:00:05 JST" name="launchApplication" finished-at="2025-03-15T21:00:40 JST" duration-ms="34330" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder()[pri:0, instance:automation.test.ErrorValidationsTest@5b799640]" started-at="2025-03-15T21:00:40 JST" name="submitOrder" finished-at="2025-03-15T21:00:41 JST" duration-ms="1515" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at automation.test.ErrorValidationsTest.submitOrder(ErrorValidationsTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:automation.test.ErrorValidationsTest@5b799640]" started-at="2025-03-15T21:00:41 JST" name="tearDown" finished-at="2025-03-15T21:00:41 JST" duration-ms="124" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- automation.test.ErrorValidationsTest -->
    </test> <!-- Error Validation Test -->
  </suite> <!-- Suite -->
</testng-results>
